name: MagistersMonths
version: 0.1.0
main: io.github.liamvi.magistersmonths.MagistersMonths
api-version: 1.19
commands:
  calendar:
    description: Request the current date & time.
    usage: /calendar